"""buildings table

Revision ID: 11ed9366804d
Revises: 
Create Date: 2019-04-23 10:31:36.916965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11ed9366804d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_building_name'), 'building', ['name'], unique=True)
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_name'), 'room', ['name'], unique=True)
    op.create_table('telemetric_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(precision=64), nullable=True),
    sa.Column('pressure', sa.Float(precision=64), nullable=True),
    sa.Column('humidity', sa.Float(precision=64), nullable=True),
    sa.Column('IAQ', sa.Float(precision=64), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telemetric_data')
    op.drop_index(op.f('ix_room_name'), table_name='room')
    op.drop_table('room')
    op.drop_index(op.f('ix_building_name'), table_name='building')
    op.drop_table('building')
    # ### end Alembic commands ###
